name: Convert README to PDF
on:
  push:
    paths:
      - '**/README.md'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Convert PDFs
        run: |
          CONFIG_FILE=".github/workflows/pdf-config.json"
          
          # 获取PDF选项
          PDF_OPTIONS=$(jq -c '.pdfOptions' $CONFIG_FILE)
          
          # 创建临时配置文件
          echo "$PDF_OPTIONS" > .md2pdf.json
          
          # 遍历每种语言
          jq -r '.languages | to_entries[] | [.key, .value.inputFile, .value.outputFile] | @tsv' $CONFIG_FILE | while IFS=$'\t' read -r lang input output; do
            echo "Processing $lang..."
            md-to-pdf "$input" --config-file .md2pdf.json --output "$output"
          done

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-cheatsheets
          path: |
            zh/obsidian-cheatsheet_zh.pdf
            en/obsidian-cheatsheet_en.pdf
            de/obsidian-cheatsheet_de.pdf
          retention-days: 90
