name: Convert README to PDF
on:
  push:
    paths:
      - '**/README.md'
      - '.github/workflows/convert-to-pdf.yml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Chinese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install dependencies
        run: |
          npm init -y
          npm install marked puppeteer

      - name: Convert PDFs
        id: convert
        run: |
          for lang in zh en de; do
            echo "Processing $lang..."
            INPUT_FILE="${lang}/README.md"
            OUTPUT_FILE="${lang}/obsidian-cheatsheet_${lang}.pdf"
            
            if [ -f "$INPUT_FILE" ]; then
              mkdir -p "$(dirname "$OUTPUT_FILE")"
              node .github/workflows/convert.js "$lang" "$INPUT_FILE" "$OUTPUT_FILE"
            fi
          done

      - name: Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Update PDF files'
          file_pattern: '**/obsidian-cheatsheet_*.pdf'
